FROM ubuntu:bionic

ENV HOME /root

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get -y install --no-install-recommends \
        software-properties-common \
        wget \
        build-essential \
        python-dev \
        python3-dev

RUN wget https://www.salome-platform.org/downloads/previous-versions/salome-v9.3/DownloadDistr?platform=OS1.UB18.04&version=9.3.0

RUN apt-get -y remove \
        software-properties-common \
        wget
RUN apt-get clean apt-get autoremove

WORKDIR $HOME