FROM ubuntu:bionic

ENV HOME /root

ARG salome_download_path

RUN apt-get update -y && apt-get -y install --no-install-recommends \
    # software-properties-common is required for wget
    software-properties-common wget \
    # if python 3 is not explicitly installed, then autoremove will remove it
    python3 \
    # net-tools is required for Salome 9.x
    net-tools \
    # libtbb2 is required for Salome 9.5
    libtbb2 \
    # libgfortran
    libgfortran4 \
    # needed by the GEOM module (see https://github.com/tianyikillua/code_aster_on_docker/issues/4)
    libglu1-mesa libxmu6 \
    # install libpng16
    libpng16-16 \
    # install libfontconfig for qt
    libfontconfig && \
    libicu55 && \
    rm -rf /var/lib/apt/lists/* && \
    # getting salome
    wget -nv ${salome_download_path} -O salome_dir.tar.gz && \
    tar xzf salome_dir.tar.gz && \
    rm salome_dir.tar.gz && \
    # the next command might not work for all cases
    mv SALOME* $HOME/salome_dir && \
    # remove unnecessary files
    rm -rf $HOME/salome_dir/ARCHIVES/ && \
    rm -rf $HOME/salome_dir/SOURCES/ && \
    # remove unnecessary binaries - be careful here, some binaries are required for testing!
    rm -rf $HOME/salome_dir/BINARIES*/llvm/ && \
    rm -rf $HOME/salome_dir/BINARIES*/cppunit/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MED/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MEDCOUPLING/ && \
    rm -rf $HOME/salome_dir/BINARIES*/mesa/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MeshGems/ && \
    rm -rf $HOME/salome_dir/BINARIES*/FIELDS/ && \
    rm -rf $HOME/salome_dir/BINARIES*/cmake/ && \
    rm -rf $HOME/salome_dir/BINARIES*/YACS/ && \
    rm -rf $HOME/salome_dir/BINARIES*/HOMARD/ && \
    rm -rf $HOME/salome_dir/BINARIES*/homard_bin/ && \
    rm -rf $HOME/salome_dir/BINARIES*/PARAVIS/ && \
    rm -rf $HOME/salome_dir/BINARIES*/HEXABLOCK/ && \
    rm -rf $HOME/salome_dir/BINARIES*/doxygen/ && \
    # cleanup
    apt-get -y remove \
        software-properties-common wget && \
    apt-get clean && apt-get autoremove -y

CMD ["${HOME}/salome_dir/salome"]

WORKDIR $HOME
