FROM ubuntu:bionic

ENV HOME /root

ARG salome_download_path

RUN apt-get update -y && apt-get -y install --no-install-recommends \
    # software-properties-common is required for wget
    software-properties-common wget \
    # libssl1.0-dev is required for Salome 8.4 & 8.5 (install before python2) => https://stackoverflow.com/questions/20399331/error-importing-hashlib-with-python-2-7-but-not-with-2-6#comment97786717_20419131
    libssl1.0-dev \
    # python 2 is required to execute Salome < 9 (dev bcs 8.3 needs it)
    python-dev \
    # libxml2 is required for Salome 8.3
    libxml2 \
    && rm -rf /var/lib/apt/lists/* && \
    # getting salome
    wget -nv ${salome_download_path} -O salome_dir.tar.gz && \
    tar xzf salome_dir.tar.gz && \
    rm salome_dir.tar.gz && \
    # the next command might not work for all cases
    mv SALOME* $HOME/salome_dir && \
    # remove unnecessary files
    rm -rf $HOME/salome_dir/ARCHIVES/ && \
    rm -rf $HOME/salome_dir/SOURCES/ && \
    # remove unnecessary binaries - be careful here, some binaries are required for testing!
    rm -rf $HOME/salome_dir/BINARIES*/ParaView/ && \
    rm -rf $HOME/salome_dir/BINARIES*/llvm/ && \
    rm -rf $HOME/salome_dir/BINARIES*/cppunit/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MED/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MEDCOUPLING/ && \
    # cleanup
    apt-get -y remove \
        software-properties-common wget && \
    apt-get clean && apt-get autoremove -y

CMD ["${HOME}/salome_dir/salome"]

WORKDIR $HOME
