FROM ubuntu:bionic

ENV HOME /root

ARG salome_download_path

RUN apt-get update -y && apt-get -y install --no-install-recommends \
    # software-properties-common is required for wget
    software-properties-common wget \
    # if python 3 is not explicitly installed, then autoremove will remove it
    python3 \
    # libxml2 is required for Salome 8.3
    libxml2 \
    # net-tools is required for Salome 8.x
    net-tools \
    && rm -rf /var/lib/apt/lists/* && \
    # getting salome
    wget -nv ${salome_download_path} -O salome_dir.tar.gz && \
    tar xzf salome_dir.tar.gz && \
    rm salome_dir.tar.gz && \
    # the next command might not work for all cases
    mv SALOME* $HOME/salome_dir && \
    # remove unnecessary files
    rm -rf $HOME/salome_dir/ARCHIVES/ && \
    rm -rf $HOME/salome_dir/SOURCES/ && \
    # remove unnecessary binaries - be careful here, some binaries are required for testing!
    rm -rf $HOME/salome_dir/BINARIES*/ParaView/ && \
    rm -rf $HOME/salome_dir/BINARIES*/llvm/ && \
    rm -rf $HOME/salome_dir/BINARIES*/cppunit/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MED/ && \
    rm -rf $HOME/salome_dir/BINARIES*/MEDCOUPLING/ && \
    # cleanup
    apt-get -y remove \
        software-properties-common wget && \
    apt-get clean && apt-get autoremove -y

CMD ["${HOME}/salome_dir/salome"]

WORKDIR $HOME
